version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=postgres
      - PASSWORD=tft
      - DBNAME=todo-app
      - PORT=5432
    restart: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tft
      POSTGRES_DB: todo-app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
